apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "elasticsearch.fullname" . }}-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: master
