apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
stringData:
  confidant.server.auth.key: {{ .Values.confidant.serverAuthKey | quote }}
  confidant.session.secret: {{ .Values.confidant.sessionSecret | quote }}
  saml.sp.key.file.password: {{ .Values.saml.spKeyFilePassword | quote }}
