apiVersion: v1
kind: Secret
metadata:
  name: certs
type: Opaque
stringData:
  saml.sp.cert: |
{{ .Values.saml.spCert | indent 4 }}
  saml.sp.key: |
{{ .Values.saml.spKey | indent 4 }}
  saml.idp.cert: |
{{ .Values.saml.idpCert | indent 4 }}
