apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "elasticsearch.fullname" . }}-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "elasticsearch.fullname" . }}-client
  minReplicas: {{ .Values.replicaCount.client }}
  maxReplicas: {{ mul .Values.replicaCount.client ( .Values.replicaScaleFactor.client | default 2 ) }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.cpuThreshold | default "70%" }}
