{{ $root := . }}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: master
spec:
  serviceName: {{ template "fullname" . }}-master
  {{- if ge .Capabilities.KubeVersion.Minor "7" }}
  podManagementPolicy: "Parallel"
  {{- end }}
  replicas: {{ .Values.replicaCount.master }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: master
    spec:
      securityContext:
        fsGroup: 1000
      {{- if .Values.affinityEnabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Avoid scheduling on same node:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "name" . }}
                topologyKey: kubernetes.io/hostname
            # Spread out across AZs:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "name" . }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ES_NODE_NAME
              value: master-${HOSTNAME}
            - name: ES_NODE_MASTER
              value: "true"

            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_SERVICE
              value: {{ template "fullname" . }}-transport

            - name: ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: es.discovery.zen.minimum.master.nodes

            - name: ES_GATEWAY_EXPECTED_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: es.gateway.expected_data_nodes

            - name: ES_GATEWAY_RECOVER_AFTER_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: es.discovery.zen.minimum.master.nodes

            - name: ES_GATEWAY_RECOVER_AFTER_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: es.gateway.recover_after_time

            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: es.java.opts.master

          {{- range $key, $value := .Values.config }}
            - name: {{ $key | upper | replace "." "_" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" $root }}
                  key: {{ $key }}
          {{- end }}

          ports:
            - name: transport
              containerPort: {{ .Values.service.ports.transport.internalPort }}
            - name: http
              containerPort: {{ .Values.service.ports.http.internalPort }}

          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.http.internalPort }}
            initialDelaySeconds: 600
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.http.internalPort }}
            initialDelaySeconds: 10
            periodSeconds: 5

          volumeMounts:
            - name: {{ template "fullname" . }}-master
              mountPath: /usr/share/elasticsearch/data
              readOnly: false

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: {{ template "fullname" . }}-master
        annotations:
        {{- range $key, $value := .Values.persistentVolumes.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: {{ .Values.persistentVolumes.master.size }}
        selector:
          matchLabels:
            app: {{ template "name" . }}
            component: master
            uuid: {{ .Values.persistentVolumes.uuid }}
