apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    helm.sh/chart: {{ include "elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  serviceName: {{ include "elasticsearch.fullname" . }}
  replicas: {{ .Values.master.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default "5" }}
  podManagementPolicy: {{ .Values.podManagementPolicy | default "Parallel" }}
  strategy:
    type: {{ .Values.strategyType | default "OnDelete" }}
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: master
    spec:
      serviceAccountName: {{ include "elasticsearch.fullname" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ES_NODE_NAME
              value: master-${HOSTNAME}
            - name: ES_NODE_MASTER
              value: "true"
            - name: ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.discovery.zen.ping.unicast.hosts
            - name: ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.discovery.zen.minimum.master.nodes
            - name: ES_GATEWAY_RECOVER_AFTER_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.recover_after_data_nodes
            - name: ES_GATEWAY_EXPECTED_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.expected_data_nodes
            - name: ES_GATEWAY_RECOVER_AFTER_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.recover_after_time
          {{- range $key, $value := .Values.config }}
            - name: {{ $key | upper | replace "." "_" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" $ }}
                  key: {{ $key }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/kill", "-15", "1"]
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
          volumeMounts:
            - name: {{ include "elasticsearch.fullname" . }}-master
              mountPath: /usr/share/elasticsearch/data
              readOnly: false
          resources:
{{ toYaml .Values.master.resources | indent 12 }}
    {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.master.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.master.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: {{ include "elasticsearch.fullname" . }}-master
    spec:
      finalizers:
      - kubernetes.io/pvc-protection
      - kubernetes.io/pv-protection
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ include "elasticsearch.fullname" . }}
      resources:
        requests:
          storage: {{ .Values.persistence.masterSize }}
