apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.config | indent 2 -}}
  es.discovery.zen.minimum.master.nodes: {{ div .Values.replicaCount.master 2 | add 1  | quote }}
  es.gateway.recover_after_data_nodes: {{ div .Values.replicaCount.data 3 | mul 2 | quote }}
  es.gateway.expected_data_nodes: {{ .Values.replicaCount.data | quote }}
  es.gateway.recover_after_time: {{ printf "%sm" (add 5 .Values.replicaCount.data | toString) | quote }}
