{{- if .Values.exporterEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}-exporter
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: metrics
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  ports:
    - port: 9108
      targetPort: 9108
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    component: exporter
{{- end }}